input_folder: inbox
output_folder: outbox

logs_level: error
logs_file: logs.txt

categories:
  - Спам:
    - word: банковской карты
      weight: 5
    - word: скидка
      weight: 5
    - word: верификация
      weight: 4
    - word: розыгрыш
      weight: 4
    - word: победителем
      weight: 4
    - word: приз
      weight: 4
    - word: exclusive offer
      weight: 4
    - word: limited time
      weight: 4
    - word: аккаунт
      weight: 2
    - word: логин
      weight: 2
    - word: пароль
      weight: 2
    - word: введите
      weight: 1
    - word: ссылке
      weight: 1

  - Сбои и инциденты:
    - word: ошибка 500
      weight: 5
    - word: ремонт
      weight: 5
    - word: работа остановлена
      weight: 5
    - word: не отвечает
      weight: 5
    - word: недоступен
      weight: 5
    - word: диагностику
      weight: 5
    - word: не работает
      weight: 4
    - word: работало
      weight: 4
    - word: инцидент
      weight: 4
    - word: перестал
      weight: 4
    - word: неисправность
      weight: 4
    - word: зависает
      weight: 3
    - word: сбой
      weight: 3
    - word: падает
      weight: 3
    - word: сломался
      weight: 3
    - word: не запускается
      weight: 3
    - word: ошибка
      weight: 2
    - word: healthcheck
      weight: 2
    - word: авторизации
      weight: 2

  - Запросы на доступ:
    - word: запрос доступа
      weight: 5
    - word: нужны права
      weight: 5
    - word: только чтение
      weight: 5
    - word: vpn
      weight: 4
    - word: gitlab
      weight: 4
    - word: confluence
      weight: 4
    - word: восстановить
      weight: 3
    - word: временного
      weight: 3
    - word: облачное хранилище
      weight: 3
    - word: система согласования
      weight: 3
    - word: согласование
      weight: 3
    - word: доступ
      weight: 2
    - word: доступа
      weight: 2
    - word: права
      weight: 2
    - word: почта
      weight: 1

  - Кадровые вопросы:
    - word: больничный лист
      weight: 5
    - word: отпуск
      weight: 5
    - word: сотрудника
      weight: 4
    - word: больничный
      weight: 4
    - word: рабочее место
      weight: 4
    - word: подготовить
      weight: 2

  - Документы и уведомления:
    - word: закрывающие документы
      weight: 5
    - word: статус задач
      weight: 5
    - word: договор
      weight: 4
    - word: акт
      weight: 4
    - word: созвон
      weight: 4
    - word: техническое задание
      weight: 4
    - word: финальная версия
      weight: 4
    - word: плановый отчет
      weight: 4
    - word: дайджест
      weight: 3
    - word: демо
      weight: 3
    - word: мониторинга
      weight: 3
    - word: правки
      weight: 3
    - word: обновления корпоративного портала
      weight: 3
    - word: документы
      weight: 2
    - word: обсудить
      weight: 2
    - word: счёт
      weight: 2
    - word: оплата
      weight: 2
    - word: перенос созвона
      weight: 2
