input_folder: inbox
output_folder: outbox

logs_file: logs.txt

categories:
  - Авария:
    - word: не отвечает
      weight: 1
    - word: ошибка 500
      weight: 1
    - word: работа полностью остановлена
      weight: 1
    - word: массовый сбой
      weight: 1
    - word: критичный инцидент
      weight: 1
    - word: уже * минут
      weight: 1
    - word: не работает у всего отдела
      weight: 1
    - word: срочно проверить
      weight: 1
    - word: недоступен
      weight: 1
    - word: второй запрос
      weight: 1
    - word: повторно
      weight: 1

  - Сбой:
    - word: не работает
      weight: 1
    - word: ошибка
      weight: 1
    - word: зависает
      weight: 1
    - word: не открывает файлы
      weight: 1
    - word: не запускается
      weight: 1
    - word: не устанавливается
      weight: 1
    - word: не включается
      weight: 1
    - word: после обновления
      weight: 1
    - word: переустановка не помогла
      weight: 1
    - word: раньше всё работало
      weight: 1

  - Запрос доступа:
    - word: выдать доступ
      weight: 1
    - word: подготовить рабочее место
      weight: 1
    - word: доступы для нового сотрудника
      weight: 1
    - word: нужны права
      weight: 1
    - word: прошу восстановить доступ
      weight: 1
    - word: перевод в отдел
      weight: 1
    - word: пропал доступ
      weight: 1
    - word: временный доступ
      weight: 1
    - word: чтение и редактирование
      weight: 1

  - Замена оборудования:
    - word: замена
      weight: 1
    - word: диагностика
      weight: 1
    - word: не определяется системой
      weight: 1
    - word: сломался
      weight: 1
    - word: не включается
      weight: 1
    - word: издаёт посторонние звуки
      weight: 1
    - word: ноутбук
      weight: 1
    - word: гарнитура
      weight: 1
    - word: принтер
      weight: 1
    - word: мышь
      weight: 1
      
  - Документы:
    - word: cчёт
      weight: 1
    - word: акт
      weight: 1
    - word: договор
      weight: 1
    - word: инструкция
      weight: 1
    - word: согласовать
      weight: 1
    - word: закрывающие документы
      weight: 1
    - word: версия
      weight: 1
    - word: правки
      weight: 1

  - Плановые работы:
    - word: дайджест
      weight: 1
    - word: healthcheck
      weight: 1
    - word: alert
      weight: 1
    - word: отчёт мониторинга
      weight: 1
    - word: upgrade
      weight: 1
    - word: cpu usage
      weight: 1
    - word: disk usage
      weight: 1

  - Спам:
    - word: вы выиграли
      weight: 1
    - word: подозрительный вход
      weight: 1
    - word: подтвердите личность
      weight: 1
    - word: введите логин и пароль
      weight: 1
    - word: скидка
      weight: 1
    - word: эксклюзивная акция
      weight: 1
    - word: http
      weight: 1
    - word: ваш аккаунт будет заблокирован
      weight: 1

  - Кадры:
    - word: отпуск
      weight: 1
    - word: больничный лист 
      weight: 1
    - word: период нетрудоспособности
      weight: 1
    - word: согласовать отпуск
      weight: 1
    - word: направляю больничный
      weight: 1

  - Встреча:
    - word: созвон
      weight: 1
    - word: демо
      weight: 1
    - word: обсудить статус задач
      weight: 1
    - word: встретиться по отчёту
      weight: 1

  - Клиент:
    - word: клиент
      weight: 1
    - word: партнёр
      weight: 1
    - word: жалоба
      weight: 1
    - word: внешний пользователь
      weight: 1
    - word: api
      weight: 1
    - word: ошибка при подключении
      weight: 1
    - word: не может зарегистрироваться
      weight: 1
    - word: запрос от внешнего пользователя
      weight: 1

  - Переадресовано:
    - word: forwarded message
      weight: 1
    - word: перенаправляю
      weight: 1
    - word: не знаю, к кому обращаться
      weight: 1
    - word: fwd
      weight: 1
